"""empty message

Revision ID: 8e3b4e64e317
Revises: 2a7f45706eb8
Create Date: 2026-01-04 15:55:06.882807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e3b4e64e317'
down_revision = '2a7f45706eb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_momos_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_momos_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
